import { createClient } from "@/lib/supabase-server";
import { getOutbreaks, getLocalizedDisease, getLocalizedCountry } from "@/lib/outbreaks";
import { PrintButton } from "@/components/PrintButton";
import { LayoutDashboard } from "lucide-react";

export const dynamic = "force-dynamic";

const COPY = {
  fr: {
    title: "Briefing Exécutif",
    subtitle: "Situation épidémiologique mondiale — ",
    planRequired: "Accès réservé aux plans Pro, Équipe et Enterprise.",
    upgrade: "Passer à Pro",
    print: "Imprimer / PDF",
    cases: "cas", deaths: "décès",
    actions: {
      high: "Action immédiate requise — ce foyer présente un risque grave pour la santé publique.",
      medium: "Surveillance renforcée recommandée — suivi hebdomadaire prioritaire.",
      low: "Suivi standard — aucune action urgente requise.",
    },
    riskLabels: { high: "Risque élevé", medium: "Risque moyen", low: "Risque faible" },
    poweredBy: "Rapport généré par HealthWatch Global",
    noOutbreaks: "Aucun foyer actif à signaler.",
    topRisks: "Principales menaces actives",
    viewFull: "Voir le sitrep complet",
    back: "Retour au tableau de bord",
    loginRequired: "Connexion requise",
  },
  en: {
    title: "Executive Briefing",
    subtitle: "Global epidemic situation — ",
    planRequired: "Access restricted to Pro, Team, and Enterprise plans.",
    upgrade: "Upgrade to Pro",
    print: "Print / PDF",
    cases: "cases", deaths: "deaths",
    actions: {
      high: "Immediate action required — this outbreak poses a serious public health threat.",
      medium: "Enhanced surveillance recommended — prioritize weekly follow-up.",
      low: "Standard monitoring — no urgent action required.",
    },
    riskLabels: { high: "High risk", medium: "Medium risk", low: "Low risk" },
    poweredBy: "Report generated by HealthWatch Global",
    noOutbreaks: "No active outbreaks to report.",
    topRisks: "Top active threats",
    viewFull: "View full sitrep",
    back: "Back to dashboard",
    loginRequired: "Login required",
  },
  es: {
    title: "Informe Ejecutivo",
    subtitle: "Situación epidemiológica mundial — ",
    planRequired: "Acceso restringido a los planes Pro, Team y Enterprise.",
    upgrade: "Actualizar a Pro",
    print: "Imprimir / PDF",
    cases: "casos", deaths: "fallecidos",
    actions: {
      high: "Se requiere acción inmediata — este brote representa una amenaza grave para la salud pública.",
      medium: "Se recomienda vigilancia reforzada — priorizar seguimiento semanal.",
      low: "Seguimiento estándar — no se requiere acción urgente.",
    },
    riskLabels: { high: "Riesgo alto", medium: "Riesgo medio", low: "Riesgo bajo" },
    poweredBy: "Informe generado por HealthWatch Global",
    noOutbreaks: "No hay brotes activos que informar.",
    topRisks: "Principales amenazas activas",
    viewFull: "Ver sitrep completo",
    back: "Volver al panel",
    loginRequired: "Inicio de sesión requerido",
  },
  ar: {
    title: "الإحاطة التنفيذية",
    subtitle: "الوضع الوبائي العالمي — ",
    planRequired: "الوصول محجوز لخطط Pro وTeam وEnterprise.",
    upgrade: "الترقية إلى Pro",
    print: "طباعة / PDF",
    cases: "حالة", deaths: "وفاة",
    actions: {
      high: "مطلوب إجراء فوري — يُشكّل هذا التفشي تهديداً خطيراً للصحة العامة.",
      medium: "يُنصح بتعزيز المراقبة — إعطاء أولوية للمتابعة الأسبوعية.",
      low: "المتابعة الاعتيادية — لا يتطلب الأمر إجراءً عاجلاً.",
    },
    riskLabels: { high: "خطر مرتفع", medium: "خطر متوسط", low: "خطر منخفض" },
    poweredBy: "تقرير صادر عن HealthWatch Global",
    noOutbreaks: "لا توجد تفشيات نشطة للإبلاغ عنها.",
    topRisks: "أبرز التهديدات النشطة",
    viewFull: "عرض التقرير الوبائي الكامل",
    back: "العودة إلى لوحة البيانات",
    loginRequired: "تسجيل الدخول مطلوب",
  },
  id: {
    title: "Laporan Eksekutif",
    subtitle: "Situasi epidemi global — ",
    planRequired: "Akses terbatas untuk paket Pro, Team, dan Enterprise.",
    upgrade: "Upgrade ke Pro",
    print: "Cetak / PDF",
    cases: "kasus", deaths: "kematian",
    actions: {
      high: "Tindakan segera diperlukan — wabah ini menimbulkan ancaman serius bagi kesehatan masyarakat.",
      medium: "Pengawasan yang ditingkatkan direkomendasikan — prioritaskan tindak lanjut mingguan.",
      low: "Pemantauan standar — tidak diperlukan tindakan mendesak.",
    },
    riskLabels: { high: "Risiko tinggi", medium: "Risiko sedang", low: "Risiko rendah" },
    poweredBy: "Laporan dibuat oleh HealthWatch Global",
    noOutbreaks: "Tidak ada wabah aktif untuk dilaporkan.",
    topRisks: "Ancaman aktif utama",
    viewFull: "Lihat sitrep lengkap",
    back: "Kembali ke dasbor",
    loginRequired: "Login diperlukan",
  },
};

const RISK_ORDER: Record<string, number> = { high: 0, medium: 1, low: 2 };

const RISK_COLORS = {
  high: {
    bg: "bg-red-950/60", border: "border-red-500/30",
    badge: "bg-red-500/20 text-red-300 border-red-500/40",
    action: "text-red-300",
  },
  medium: {
    bg: "bg-amber-950/60", border: "border-amber-500/30",
    badge: "bg-amber-500/20 text-amber-300 border-amber-500/40",
    action: "text-amber-300",
  },
  low: {
    bg: "bg-emerald-950/60", border: "border-emerald-500/30",
    badge: "bg-emerald-500/20 text-emerald-300 border-emerald-500/40",
    action: "text-emerald-400",
  },
};

export default async function BriefingPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const c = COPY[locale as keyof typeof COPY] ?? COPY.en;
  const isRtl = locale === "ar";

  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return (
      <div className="min-h-screen bg-gray-950 flex items-center justify-center p-6">
        <div className="text-center space-y-3">
          <p className="text-gray-400 text-sm">{c.loginRequired}</p>
          <a href={`/${locale}`} className="text-red-400 hover:text-red-300 text-sm underline">← {c.back}</a>
        </div>
      </div>
    );
  }

  const { data: profile } = await supabase
    .from("profiles").select("plan").eq("id", user.id).single();
  const isPaid = ["pro", "team", "enterprise"].includes(profile?.plan ?? "");

  if (!isPaid) {
    return (
      <div className="min-h-screen bg-gray-950 flex items-center justify-center p-6">
        <div className="text-center space-y-4 max-w-sm">
          <div className="w-12 h-12 rounded-full bg-red-900/30 border border-red-700/30 flex items-center justify-center mx-auto">
            <LayoutDashboard className="w-6 h-6 text-red-400" />
          </div>
          <h2 className="text-white font-semibold">{c.title}</h2>
          <p className="text-gray-400 text-sm">{c.planRequired}</p>
          <a
            href={`/${locale}`}
            className="inline-block px-4 py-2 bg-red-600 hover:bg-red-500 text-white text-sm font-semibold rounded-lg transition-colors"
          >
            {c.upgrade}
          </a>
        </div>
      </div>
    );
  }

  const allOutbreaks = await getOutbreaks();
  const sorted = [...allOutbreaks]
    .sort((a, b) => (RISK_ORDER[a.risk_level] ?? 3) - (RISK_ORDER[b.risk_level] ?? 3) || b.cases - a.cases)
    .slice(0, 5);

  const today = new Date().toLocaleDateString(
    locale === "fr" ? "fr-FR"
    : locale === "es" ? "es-ES"
    : locale === "ar" ? "ar-SA"
    : locale === "id" ? "id-ID"
    : "en-GB",
    { day: "numeric", month: "long", year: "numeric" }
  );

  return (
    <div
      dir={isRtl ? "rtl" : "ltr"}
      className="min-h-screen bg-gray-950 text-white p-4 sm:p-8 print:bg-white print:text-black"
    >
      <div className="max-w-3xl mx-auto space-y-6">

        {/* Header */}
        <div className="flex items-start justify-between gap-4 print:pb-4 print:border-b print:border-gray-300">
          <div>
            <div className="flex items-center gap-2 mb-1 print:hidden">
              <div className="w-2.5 h-2.5 rounded-full bg-red-400" />
              <span className="text-[10px] text-gray-500 uppercase tracking-widest font-medium">HealthWatch Global</span>
            </div>
            <h1 className="text-2xl sm:text-3xl font-bold print:text-2xl print:text-black">{c.title}</h1>
            <p className="text-sm text-gray-400 mt-1 print:text-gray-600">{c.subtitle}{today}</p>
          </div>
          <PrintButton label={c.print} />
        </div>

        {/* Top threats */}
        <section>
          <h2 className="text-[10px] font-semibold text-gray-500 uppercase tracking-widest mb-4 print:text-gray-700">
            {c.topRisks}
          </h2>

          {sorted.length === 0 ? (
            <p className="text-gray-500 text-sm">{c.noOutbreaks}</p>
          ) : (
            <div className="space-y-3">
              {sorted.map((outbreak, i) => {
                const colors = RISK_COLORS[outbreak.risk_level] ?? RISK_COLORS.low;
                const disease = getLocalizedDisease(outbreak, locale);
                const country = getLocalizedCountry(outbreak, locale);
                const cfr = outbreak.cases > 0
                  ? (outbreak.deaths / outbreak.cases * 100).toFixed(1)
                  : null;

                return (
                  <div
                    key={outbreak.id}
                    className={`rounded-xl border p-4 sm:p-5 ${colors.bg} ${colors.border} print:border print:rounded-lg print:bg-white`}
                  >
                    {/* Row 1: rank + name + badge */}
                    <div className="flex items-start justify-between gap-3 mb-3">
                      <div className="flex items-start gap-3 min-w-0">
                        <span className="text-lg font-black text-gray-700 print:text-gray-300 leading-none mt-0.5 shrink-0 tabular-nums">
                          {String(i + 1).padStart(2, "0")}
                        </span>
                        <div className="min-w-0">
                          <p className="font-bold text-base sm:text-lg leading-tight print:text-black">{disease}</p>
                          <p className="text-sm text-gray-400 print:text-gray-600 mt-0.5">{country}</p>
                        </div>
                      </div>
                      <span className={`px-2.5 py-1 rounded-full text-xs font-semibold border shrink-0 ${colors.badge} print:bg-transparent print:text-black print:border-gray-400`}>
                        {c.riskLabels[outbreak.risk_level]}
                      </span>
                    </div>

                    {/* Row 2: stats */}
                    <div className="flex items-center gap-4 text-sm mb-3 flex-wrap">
                      <span className="font-mono font-semibold text-gray-200 print:text-black">
                        {outbreak.cases.toLocaleString("en")}
                        <span className="font-normal text-gray-500 print:text-gray-600 ml-1">{c.cases}</span>
                      </span>
                      {outbreak.deaths > 0 && (
                        <span className="text-gray-400 print:text-gray-600">
                          {outbreak.deaths.toLocaleString("en")}
                          <span className="ml-1">{c.deaths}</span>
                        </span>
                      )}
                      {cfr && (
                        <span className="text-xs font-semibold text-gray-400 print:text-gray-700">
                          CFR {cfr}%
                        </span>
                      )}
                      {outbreak.is_pheic && (
                        <span className="text-xs text-purple-400 font-semibold print:text-purple-700 border border-purple-700/40 rounded px-1.5 py-0.5">
                          PHEIC
                        </span>
                      )}
                    </div>

                    {/* Row 3: action recommendation */}
                    <p className={`text-xs leading-relaxed font-medium ${colors.action} print:text-gray-800 border-t border-gray-700/30 print:border-gray-200 pt-3`}>
                      → {c.actions[outbreak.risk_level]}
                    </p>
                  </div>
                );
              })}
            </div>
          )}
        </section>

        {/* Link to full sitrep */}
        <div className="text-center print:hidden pt-2">
          <a
            href={`/${locale}/sitrep`}
            className="text-sm text-gray-500 hover:text-gray-300 transition-colors underline underline-offset-2"
          >
            {c.viewFull} →
          </a>
        </div>

        {/* Print footer — viral branding */}
        <div className="hidden print:block pt-6 mt-8 border-t border-gray-300">
          <div className="flex items-center justify-between text-xs text-gray-400">
            <span className="font-semibold">{c.poweredBy}</span>
            <span>healthwatch-global.com</span>
          </div>
          <p className="mt-1 text-xs text-gray-300">{today}</p>
        </div>

        {/* Screen footer */}
        <div className="pt-4 border-t border-gray-800 text-xs text-gray-700 print:hidden">
          <a href={`/${locale}`} className="hover:text-gray-500 transition-colors">← {c.back}</a>
        </div>
      </div>
    </div>
  );
}
