// Print-optimized outbreak one-pager
// Opens in a new tab → user prints/saves as PDF via browser
// URL: /fr/outbreak/{id}/print

import { createClient } from "@supabase/supabase-js";
import { notFound } from "next/navigation";
import { getLocalizedDisease, getLocalizedCountry } from "@/lib/outbreaks";
import { getIncidenceRate, getPopulationThousands } from "@/lib/population-data";
import type { Metadata } from "next";

const BOM   = String.fromCharCode(65279);
const clean = (v: string | undefined) => (v || "").replace(new RegExp("^" + BOM), "").trim();

export async function generateMetadata({ params }: { params: Promise<{ locale: string; id: string }> }): Promise<Metadata> {
  const { id } = await params;
  return {
    title: `Outbreak Report — HealthWatch Global`,
    robots: { index: false, follow: false },
  };
}

const LABELS: Record<string, Record<string, string>> = {
  fr: {
    title: "Rapport épidémiologique",
    subtitle: "HealthWatch Global · Données OMS",
    cases: "Cas confirmés", deaths: "Décès", cfr: "Taux de létalité",
    incidence: "Incidence (/ 100 000 hab.)", date: "Date du rapport",
    region: "Région", source: "Source OMS", description: "Résumé",
    pheic: "URGENCE SANITAIRE INTERNATIONALE (PHEIC)",
    corroborated: "Confirmé par WHO + ProMED",
    noData: "Non disponible",
    generatedBy: "Rapport généré par HealthWatch Global",
    disclaimer: "Ces données proviennent de sources officielles (OMS, ProMED) et sont fournies à titre informatif uniquement. Elles ne constituent pas un avis médical.",
    print: "Imprimer / Sauvegarder en PDF",
  },
  en: {
    title: "Epidemiological Report",
    subtitle: "HealthWatch Global · WHO Data",
    cases: "Confirmed cases", deaths: "Deaths", cfr: "Case fatality rate",
    incidence: "Incidence (per 100,000 pop.)", date: "Report date",
    region: "Region", source: "WHO source", description: "Summary",
    pheic: "PUBLIC HEALTH EMERGENCY OF INTERNATIONAL CONCERN (PHEIC)",
    corroborated: "Confirmed by WHO + ProMED",
    noData: "Not available",
    generatedBy: "Report generated by HealthWatch Global",
    disclaimer: "Data sourced from official organizations (WHO, ProMED) for informational purposes only. Not medical advice.",
    print: "Print / Save as PDF",
  },
  es: {
    title: "Informe Epidemiológico",
    subtitle: "HealthWatch Global · Datos OMS",
    cases: "Casos confirmados", deaths: "Fallecidos", cfr: "Tasa de letalidad",
    incidence: "Incidencia (por 100.000 hab.)", date: "Fecha del informe",
    region: "Región", source: "Fuente OMS", description: "Resumen",
    pheic: "EMERGENCIA DE SALUD PÚBLICA DE IMPORTANCIA INTERNACIONAL (ESPII)",
    corroborated: "Confirmado por WHO + ProMED",
    noData: "No disponible",
    generatedBy: "Informe generado por HealthWatch Global",
    disclaimer: "Datos de fuentes oficiales (OMS, ProMED) solo para información. No es consejo médico.",
    print: "Imprimir / Guardar como PDF",
  },
  ar: {
    title: "التقرير الوبائي",
    subtitle: "HealthWatch Global · بيانات OMS",
    cases: "الحالات المؤكدة", deaths: "الوفيات", cfr: "معدل الوفيات",
    incidence: "معدل الإصابة (لكل 100,000)", date: "تاريخ التقرير",
    region: "المنطقة", source: "مصدر OMS", description: "ملخص",
    pheic: "طوارئ الصحة العمومية التي تثير قلقاً دولياً",
    corroborated: "مؤكد من WHO + ProMED",
    noData: "غير متاح",
    generatedBy: "تقرير صادر عن HealthWatch Global",
    disclaimer: "البيانات من مصادر رسمية (OMS، ProMED) للأغراض الإعلامية فقط. ليست نصيحة طبية.",
    print: "طباعة / حفظ كـ PDF",
  },
  id: {
    title: "Laporan Epidemiologi",
    subtitle: "HealthWatch Global · Data WHO",
    cases: "Kasus terkonfirmasi", deaths: "Kematian", cfr: "Tingkat kematian",
    incidence: "Insidensi (per 100.000 penduduk)", date: "Tanggal laporan",
    region: "Wilayah", source: "Sumber WHO", description: "Ringkasan",
    pheic: "KEDARURATAN KESEHATAN MASYARAKAT YANG MERESAHKAN DUNIA (KKMMD)",
    corroborated: "Dikonfirmasi oleh WHO + ProMED",
    noData: "Tidak tersedia",
    generatedBy: "Laporan dibuat oleh HealthWatch Global",
    disclaimer: "Data dari sumber resmi (WHO, ProMED) hanya untuk informasi. Bukan saran medis.",
    print: "Cetak / Simpan sebagai PDF",
  },
};

const RISK_LABEL: Record<string, Record<string, string>> = {
  high:   { fr: "RISQUE ÉLEVÉ", en: "HIGH RISK", es: "RIESGO ALTO", ar: "خطر عالٍ", id: "RISIKO TINGGI" },
  medium: { fr: "RISQUE MODÉRÉ", en: "MEDIUM RISK", es: "RIESGO MEDIO", ar: "خطر متوسط", id: "RISIKO SEDANG" },
  low:    { fr: "RISQUE FAIBLE", en: "LOW RISK", es: "RIESGO BAJO", ar: "خطر منخفض", id: "RISIKO RENDAH" },
};

const RISK_COLOR: Record<string, string> = {
  high: "#dc2626", medium: "#d97706", low: "#16a34a",
};

export default async function PrintPage({
  params,
}: {
  params: Promise<{ locale: string; id: string }>;
}) {
  const { locale, id } = await params;
  const l = LABELS[locale] ?? LABELS.en;
  const isRtl = locale === "ar";

  const supabase = createClient(
    clean(process.env.NEXT_PUBLIC_SUPABASE_URL),
    clean(process.env.SUPABASE_SERVICE_ROLE_KEY)
  );

  const { data: o } = await supabase
    .from("outbreaks")
    .select("*")
    .eq("id", id)
    .single();

  if (!o) notFound();

  const disease    = getLocalizedDisease(o, locale) ?? o.disease_en ?? o.disease;
  const country    = getLocalizedCountry(o, locale) ?? o.country_en ?? o.country;
  const hasData    = o.cases > 0;
  const cfr        = hasData ? (o.deaths / o.cases * 100).toFixed(1) + "%" : l.noData;
  const incidence  = getIncidenceRate(o.cases, o.country_en);
  const riskColor  = RISK_COLOR[o.risk_level] ?? "#6b7280";
  const riskLabel  = (RISK_LABEL[o.risk_level] ?? RISK_LABEL.low)[locale] ?? "RISK";
  const today      = new Date().toLocaleDateString(locale === "ar" ? "ar" : locale === "id" ? "id-ID" : locale, {
    year: "numeric", month: "long", day: "numeric",
  });

  return (
    <html lang={locale} dir={isRtl ? "rtl" : "ltr"}>
      <head>
        <meta charSet="UTF-8" />
        <title>{`${disease} — ${country} | HealthWatch Global`}</title>
        <style>{`
          * { box-sizing: border-box; margin: 0; padding: 0; }
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: white; color: #1e293b; font-size: 14px; line-height: 1.5; }
          @media print { .no-print { display: none !important; } @page { margin: 1.5cm; size: A4; } }
          .page { max-width: 800px; margin: 0 auto; padding: 40px 32px; }
          .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 32px; padding-bottom: 20px; border-bottom: 3px solid ${riskColor}; }
          .brand { font-size: 12px; color: #64748b; }
          .risk-badge { background: ${riskColor}15; border: 1px solid ${riskColor}40; color: ${riskColor}; padding: 4px 12px; border-radius: 99px; font-size: 11px; font-weight: 700; letter-spacing: 1px; }
          .disease-name { font-size: 32px; font-weight: 800; color: #0f172a; margin: 8px 0 4px; }
          .country { font-size: 18px; color: #64748b; }
          .pheic { background: #faf5ff; border: 1px solid #9333ea; color: #7e22ce; padding: 8px 16px; border-radius: 8px; font-size: 11px; font-weight: 700; letter-spacing: 0.5px; margin-top: 12px; display: inline-block; }
          .stats { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin: 24px 0; }
          .stat-card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; text-align: center; }
          .stat-label { font-size: 11px; color: #64748b; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 6px; }
          .stat-value { font-size: 28px; font-weight: 800; color: #0f172a; }
          .stat-value.red { color: #dc2626; }
          .stat-value.amber { color: #d97706; }
          .meta { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin: 16px 0; padding: 16px; background: #f8fafc; border-radius: 8px; border: 1px solid #e2e8f0; }
          .meta-item { font-size: 13px; }
          .meta-label { color: #64748b; margin-right: 8px; }
          .meta-value { font-weight: 600; color: #1e293b; }
          .description { margin: 20px 0; padding: 16px; background: #f8fafc; border-left: 3px solid ${riskColor}; border-radius: 0 8px 8px 0; }
          .description h3 { font-size: 12px; text-transform: uppercase; letter-spacing: 1px; color: #64748b; margin-bottom: 8px; }
          .description p { font-size: 13px; color: #334155; line-height: 1.6; }
          .badges { display: flex; gap: 8px; margin: 16px 0; flex-wrap: wrap; }
          .badge { font-size: 11px; padding: 4px 10px; border-radius: 99px; border: 1px solid; }
          .badge-blue { background: #eff6ff; border-color: #bfdbfe; color: #1d4ed8; }
          .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e2e8f0; display: flex; justify-content: space-between; font-size: 11px; color: #94a3b8; }
          .source-link { color: #dc2626; word-break: break-all; }
          .print-btn { position: fixed; bottom: 24px; right: 24px; background: #dc2626; color: white; border: none; padding: 12px 24px; border-radius: 8px; font-size: 14px; font-weight: 600; cursor: pointer; box-shadow: 0 4px 12px rgba(220,38,38,0.3); }
          .print-btn:hover { background: #b91c1c; }
        `}</style>
      </head>
      <body>
        <div className="page">

          {/* Header */}
          <div className="header">
            <div>
              <div className="brand">HealthWatch Global · {l.subtitle}</div>
              <div className="disease-name">{disease}</div>
              <div className="country">📍 {country}</div>
              {o.is_pheic && <div className="pheic">🚨 {l.pheic}</div>}
            </div>
            <div style={{ textAlign: isRtl ? "left" : "right" }}>
              <div className="risk-badge">{riskLabel}</div>
              <div style={{ fontSize: 11, color: "#94a3b8", marginTop: 8 }}>{today}</div>
            </div>
          </div>

          {/* Stats */}
          <div className="stats">
            <div className="stat-card">
              <div className="stat-label">{l.cases}</div>
              <div className="stat-value">{hasData ? o.cases.toLocaleString() : l.noData}</div>
            </div>
            <div className="stat-card">
              <div className="stat-label">{l.deaths}</div>
              <div className="stat-value red">{hasData ? o.deaths.toLocaleString() : l.noData}</div>
            </div>
            <div className="stat-card">
              <div className="stat-label">{l.cfr}</div>
              <div className="stat-value amber">{cfr}</div>
            </div>
          </div>

          {/* Meta */}
          <div className="meta">
            <div className="meta-item">
              <span className="meta-label">{l.date} :</span>
              <span className="meta-value">{o.date}</span>
            </div>
            <div className="meta-item">
              <span className="meta-label">{l.region} :</span>
              <span className="meta-value" style={{ textTransform: "capitalize" }}>{o.region}</span>
            </div>
            {incidence !== null && (
              <div className="meta-item">
                <span className="meta-label">{l.incidence} :</span>
                <span className="meta-value">{incidence.toFixed(2)}</span>
              </div>
            )}
            {getPopulationThousands(o.country_en) && (
              <div className="meta-item">
                <span className="meta-label">Population :</span>
                <span className="meta-value">{((getPopulationThousands(o.country_en) ?? 0) * 1000).toLocaleString()}</span>
              </div>
            )}
          </div>

          {/* Badges */}
          <div className="badges">
            {o.corroborated && (
              <span className="badge badge-blue">🔁 {l.corroborated}</span>
            )}
          </div>

          {/* Description */}
          {o.description && (
            <div className="description">
              <h3>{l.description}</h3>
              <p>{o.description}</p>
            </div>
          )}

          {/* Footer */}
          <div className="footer">
            <div>
              <div>{l.generatedBy} — healthwatch-global.com</div>
              <div style={{ marginTop: 4, fontSize: 10 }}>{l.disclaimer}</div>
            </div>
            {o.source && (
              <div style={{ textAlign: isRtl ? "left" : "right" }}>
                <div>{l.source} :</div>
                <a className="source-link" href={o.source}>{o.source}</a>
              </div>
            )}
          </div>

        </div>

        {/* Print button */}
        <button
          className="print-btn no-print"
          onClick={() => window.print()}
        >
          🖨️ {l.print}
        </button>

        <script dangerouslySetInnerHTML={{ __html: `
          document.querySelector('.print-btn').addEventListener('click', function() { window.print(); });
        `}} />
      </body>
    </html>
  );
}
