// Print-optimized outbreak one-pager
// Opens in a new tab → user prints/saves as PDF via browser
// URL: /fr/outbreak/{id}/print

import { createClient } from "@supabase/supabase-js";
import { createClient as createServerClient } from "@/lib/supabase-server";
import { notFound, redirect } from "next/navigation";
import { getLocalizedDisease, getLocalizedCountry, getLocalizedDescription } from "@/lib/outbreaks";
import { getResponseGuidance, RESPONSE_ACTIONS } from "@/lib/response-guidance";
import { getIncidenceRate, getPopulationThousands } from "@/lib/population-data";
import { resolvedPlan } from "@/lib/resolved-plan";
import type { Metadata } from "next";

const BOM   = String.fromCharCode(65279);
const clean = (v: string | undefined) => (v || "").replace(new RegExp("^" + BOM), "").trim();

export async function generateMetadata({ params }: { params: Promise<{ locale: string; id: string }> }): Promise<Metadata> {
  await params;
  return {
    title: `Outbreak Report — HealthWatch Global`,
    robots: { index: false, follow: false },
  };
}

const LABELS: Record<string, Record<string, string>> = {
  fr: {
    title: "Rapport épidémiologique",
    subtitle: "HealthWatch Global · Données OMS",
    cases: "Cas confirmés", deaths: "Décès", cfr: "Taux de létalité",
    incidence: "Incidence (/ 100 000 hab.)", date: "Date du rapport",
    region: "Région", source: "Source OMS", description: "Résumé",
    pheic: "URGENCE SANITAIRE INTERNATIONALE (PHEIC)",
    noData: "Non disponible",
    generatedBy: "Rapport généré par HealthWatch Global",
    disclaimer: "Outil de veille uniquement — ne constitue pas un déclencheur opérationnel. Toute décision de mobilisation d'équipes ou de ressources requiert une vérification directe auprès des sources primaires OMS/ECDC et de votre protocole institutionnel. HealthWatch Global ne saurait être tenu responsable des décisions opérationnelles prises sur la base de ce rapport.",
    print: "Imprimer / Sauvegarder en PDF",
  },
  en: {
    title: "Epidemiological Report",
    subtitle: "HealthWatch Global · WHO Data",
    cases: "Confirmed cases", deaths: "Deaths", cfr: "Case fatality rate",
    incidence: "Incidence (per 100,000 pop.)", date: "Report date",
    region: "Region", source: "WHO source", description: "Summary",
    pheic: "PUBLIC HEALTH EMERGENCY OF INTERNATIONAL CONCERN (PHEIC)",
    noData: "Not available",
    generatedBy: "Report generated by HealthWatch Global",
    disclaimer: "Situational awareness tool only — not an operational trigger. Any decision to mobilize teams or resources requires direct verification with primary WHO/ECDC sources and your institutional protocol. HealthWatch Global bears no liability for operational decisions made on the basis of this report.",
    print: "Print / Save as PDF",
  },
  es: {
    title: "Informe Epidemiológico",
    subtitle: "HealthWatch Global · Datos OMS",
    cases: "Casos confirmados", deaths: "Fallecidos", cfr: "Tasa de letalidad",
    incidence: "Incidencia (por 100.000 hab.)", date: "Fecha del informe",
    region: "Región", source: "Fuente OMS", description: "Resumen",
    pheic: "EMERGENCIA DE SALUD PÚBLICA DE IMPORTANCIA INTERNACIONAL (ESPII)",
    noData: "No disponible",
    generatedBy: "Informe generado por HealthWatch Global",
    disclaimer: "Herramienta de vigilancia únicamente — no es un disparador operacional. Cualquier decisión de movilizar equipos o recursos requiere verificación directa con fuentes primarias OMS/ECDC y el protocolo institucional. HealthWatch Global no asume responsabilidad por decisiones operacionales tomadas en base a este informe.",
    print: "Imprimir / Guardar como PDF",
  },
  ar: {
    title: "التقرير الوبائي",
    subtitle: "HealthWatch Global · بيانات OMS",
    cases: "الحالات المؤكدة", deaths: "الوفيات", cfr: "معدل الوفيات",
    incidence: "معدل الإصابة (لكل 100,000)", date: "تاريخ التقرير",
    region: "المنطقة", source: "مصدر OMS", description: "ملخص",
    pheic: "طوارئ الصحة العمومية التي تثير قلقاً دولياً",
    noData: "غير متاح",
    generatedBy: "تقرير صادر عن HealthWatch Global",
    disclaimer: "أداة رصد فقط — ليست مُحفِّزاً تشغيلياً. أي قرار بتعبئة فرق أو موارد يستلزم التحقق المباشر من المصادر الأولية لمنظمة الصحة العالمية/ECDC وبروتوكولك المؤسسي. لا تتحمل HealthWatch Global أي مسؤولية عن القرارات التشغيلية المتخذة بناءً على هذا التقرير.",
    print: "طباعة / حفظ كـ PDF",
  },
  id: {
    title: "Laporan Epidemiologi",
    subtitle: "HealthWatch Global · Data WHO",
    cases: "Kasus terkonfirmasi", deaths: "Kematian", cfr: "Tingkat kematian",
    incidence: "Insidensi (per 100.000 penduduk)", date: "Tanggal laporan",
    region: "Wilayah", source: "Sumber WHO", description: "Ringkasan",
    pheic: "KEDARURATAN KESEHATAN MASYARAKAT YANG MERESAHKAN DUNIA (KKMMD)",
    noData: "Tidak tersedia",
    generatedBy: "Laporan dibuat oleh HealthWatch Global",
    disclaimer: "Alat pemantauan saja — bukan pemicu operasional. Keputusan mobilisasi tim atau sumber daya memerlukan verifikasi langsung ke sumber primer WHO/ECDC dan protokol institusional Anda. HealthWatch Global tidak bertanggung jawab atas keputusan operasional berdasarkan laporan ini.",
    print: "Cetak / Simpan sebagai PDF",
  },
};

const RISK_LABEL: Record<string, Record<string, string>> = {
  high:   { fr: "RISQUE ÉLEVÉ", en: "HIGH RISK", es: "RIESGO ALTO", ar: "خطر عالٍ", id: "RISIKO TINGGI" },
  medium: { fr: "RISQUE MODÉRÉ", en: "MEDIUM RISK", es: "RIESGO MEDIO", ar: "خطر متوسط", id: "RISIKO SEDANG" },
  low:    { fr: "RISQUE FAIBLE", en: "LOW RISK", es: "RIESGO BAJO", ar: "خطر منخفض", id: "RISIKO RENDAH" },
};

const RISK_COLOR: Record<string, string> = {
  high: "#dc2626", medium: "#d97706", low: "#16a34a",
};

const TIER_LABEL: Record<string, Record<string, string>> = {
  immediate: { fr: "IMMÉDIAT · NOTIFIABLE RSI", en: "IMMEDIATE · IHR NOTIFIABLE", es: "INMEDIATO · NOTIFICABLE RSI", ar: "فوري · إخطار إلزامي (اللوائح الصحية الدولية)", id: "SEGERA · WAJIB LAPOR IHR" },
  rapid:     { fr: "RÉPONSE RAPIDE", en: "RAPID RESPONSE", es: "RESPUESTA RÁPIDA", ar: "استجابة سريعة", id: "RESPONS CEPAT" },
  monitor:   { fr: "SURVEILLANCE STANDARD", en: "STANDARD MONITORING", es: "VIGILANCIA ESTÁNDAR", ar: "مراقبة روتينية", id: "PEMANTAUAN STANDAR" },
};

const TIER_COLOR: Record<string, { bg: string; border: string; text: string }> = {
  immediate: { bg: "#fef2f2", border: "#dc2626", text: "#991b1b" },
  rapid:     { bg: "#fffbeb", border: "#d97706", text: "#92400e" },
  monitor:   { bg: "#f8fafc", border: "#94a3b8", text: "#475569" },
};

const FP_LABELS: Record<string, { fpGuidance: string; firstActions: string }> = {
  fr: { fpGuidance: "Guide d'action — Point focal",  firstActions: "Premières actions" },
  en: { fpGuidance: "Focal Point Guidance",           firstActions: "First actions" },
  es: { fpGuidance: "Guía del Punto focal",           firstActions: "Primeras acciones" },
  ar: { fpGuidance: "توجيهات نقطة الاتصال",          firstActions: "الإجراءات الأولى" },
  id: { fpGuidance: "Panduan Focal Point",            firstActions: "Tindakan pertama" },
};

export default async function PrintPage({
  params,
}: {
  params: Promise<{ locale: string; id: string }>;
}) {
  const { locale, id } = await params;
  const l = LABELS[locale] ?? LABELS.en;
  const isRtl = locale === "ar";

  // Auth check — PDF reports are a Pro feature
  const authClient = await createServerClient();
  const { data: { user } } = await authClient.auth.getUser();
  if (!user) redirect(`/${locale}/login?next=/${locale}/outbreak/${id}/print`);
  const { data: profile } = await authClient.from("profiles").select("plan, trial_ends_at, stripe_subscription_id").eq("id", user.id).single();
  if (resolvedPlan(profile) === "free") redirect(`/${locale}/pricing`);

  const supabase = createClient(
    clean(process.env.NEXT_PUBLIC_SUPABASE_URL),
    clean(process.env.SUPABASE_SERVICE_ROLE_KEY)
  );

  const { data: o } = await supabase
    .from("outbreaks")
    .select("*")
    .eq("id", id)
    .single();

  if (!o) notFound();

  const disease    = getLocalizedDisease(o, locale) ?? o.disease_en ?? o.disease;
  const country    = getLocalizedCountry(o, locale) ?? o.country_en ?? o.country;
  const hasData    = o.cases > 0;
  const cfr        = hasData ? (o.deaths / o.cases * 100).toFixed(1) + "%" : l.noData;
  const incidence  = getIncidenceRate(o.cases, o.country_en);
  const riskColor  = RISK_COLOR[o.risk_level] ?? "#6b7280";
  const riskLabel  = (RISK_LABEL[o.risk_level] ?? RISK_LABEL.low)[locale] ?? "RISK";
  const guidance   = getResponseGuidance(o.disease_en || o.disease);
  const tc         = TIER_COLOR[guidance.tier];
  const tierLabel  = (TIER_LABEL[guidance.tier])[locale] ?? (TIER_LABEL[guidance.tier]).en;
  const fpActions  = (RESPONSE_ACTIONS[guidance.tier][locale] ?? RESPONSE_ACTIONS[guidance.tier].en).slice(0, 3);
  const fp         = FP_LABELS[locale] ?? FP_LABELS.en;
  const today      = new Date().toLocaleDateString(locale === "ar" ? "ar-SA" : locale === "id" ? "id-ID" : locale, {
    year: "numeric", month: "long", day: "numeric",
  });

  return (
    <html lang={locale} dir={isRtl ? "rtl" : "ltr"}>
      <head>
        <meta charSet="UTF-8" />
        <title>{`${disease} — ${country} | HealthWatch Global`}</title>
        <style>{`
          * { box-sizing: border-box; margin: 0; padding: 0; }
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: white; color: #1e293b; font-size: 14px; line-height: 1.5; }
          @media print { .no-print { display: none !important; } @page { margin: 1.5cm; size: A4; } }
          .page { max-width: 800px; margin: 0 auto; padding: 40px 32px; }
          .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 32px; padding-bottom: 20px; border-bottom: 3px solid ${riskColor}; }
          .brand { font-size: 12px; color: #64748b; }
          .risk-badge { background: ${riskColor}15; border: 1px solid ${riskColor}40; color: ${riskColor}; padding: 4px 12px; border-radius: 99px; font-size: 11px; font-weight: 700; letter-spacing: 1px; }
          .disease-name { font-size: 32px; font-weight: 800; color: #0f172a; margin: 8px 0 4px; }
          .country { font-size: 18px; color: #64748b; }
          .pheic { background: #faf5ff; border: 1px solid #9333ea; color: #7e22ce; padding: 8px 16px; border-radius: 8px; font-size: 11px; font-weight: 700; letter-spacing: 0.5px; margin-top: 12px; display: inline-block; }
          .stats { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin: 24px 0; }
          .stat-card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; text-align: center; }
          .stat-label { font-size: 11px; color: #64748b; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 6px; }
          .stat-value { font-size: 28px; font-weight: 800; color: #0f172a; }
          .stat-value.red { color: #dc2626; }
          .stat-value.amber { color: #d97706; }
          .meta { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin: 16px 0; padding: 16px; background: #f8fafc; border-radius: 8px; border: 1px solid #e2e8f0; }
          .meta-item { font-size: 13px; }
          .meta-label { color: #64748b; margin-right: 8px; }
          .meta-value { font-weight: 600; color: #1e293b; }
          .description { margin: 20px 0; padding: 16px; background: #f8fafc; border-left: 3px solid ${riskColor}; border-radius: 0 8px 8px 0; }
          .description h3 { font-size: 12px; text-transform: uppercase; letter-spacing: 1px; color: #64748b; margin-bottom: 8px; }
          .description p { font-size: 13px; color: #334155; line-height: 1.6; }
          .badges { display: flex; gap: 8px; margin: 16px 0; flex-wrap: wrap; }
          .badge { font-size: 11px; padding: 4px 10px; border-radius: 99px; border: 1px solid; }
          .badge-blue { background: #eff6ff; border-color: #bfdbfe; color: #1d4ed8; }
          .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e2e8f0; display: flex; justify-content: space-between; font-size: 11px; color: #94a3b8; }
          .source-link { color: #dc2626; word-break: break-all; }
          .print-btn { position: fixed; bottom: 24px; right: 24px; background: #dc2626; color: white; border: none; padding: 12px 24px; border-radius: 8px; font-size: 14px; font-weight: 600; cursor: pointer; box-shadow: 0 4px 12px rgba(220,38,38,0.3); }
          .print-btn:hover { background: #b91c1c; }
          .tier-badge-print { display: inline-block; margin-top: 6px; background: ${tc.bg}; border: 1px solid ${tc.border}; color: ${tc.text}; padding: 3px 10px; border-radius: 99px; font-size: 10px; font-weight: 700; letter-spacing: 0.5px; }
          .fp-section { margin: 20px 0; padding: 16px; background: ${tc.bg}; border: 1px solid ${tc.border}40; border-left: 4px solid ${tc.border}; border-radius: 0 8px 8px 0; page-break-inside: avoid; }
          .fp-header { display: flex; align-items: center; justify-content: space-between; margin-bottom: 10px; }
          .fp-title { font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; color: ${tc.text}; }
          .fp-tier { font-size: 10px; font-weight: 700; color: ${tc.text}; background: white; border: 1px solid ${tc.border}; padding: 2px 8px; border-radius: 4px; }
          .fp-actions-label { font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.5px; color: ${tc.text}; opacity: 0.7; margin-bottom: 6px; }
          .fp-actions { list-style: none; }
          .fp-actions li { font-size: 12px; color: #1e293b; padding: 4px 0 4px 16px; border-bottom: 1px solid ${tc.border}20; position: relative; }
          .fp-actions li:last-child { border-bottom: none; }
          .fp-actions li::before { content: "›"; font-weight: 700; color: ${tc.text}; position: absolute; left: 0; }
        `}</style>
      </head>
      <body>
        <div className="page">

          {/* Header */}
          <div className="header">
            <div>
              <div className="brand">HealthWatch Global · {l.subtitle}</div>
              <div className="disease-name">{disease}</div>
              <div className="country">📍 {country}</div>
              {o.is_pheic && <div className="pheic">🚨 {l.pheic}</div>}
            </div>
            <div style={{ textAlign: isRtl ? "left" : "right" }}>
              <div className="risk-badge">{riskLabel}</div>
              <div className="tier-badge-print">{tierLabel}</div>
              <div style={{ fontSize: 11, color: "#94a3b8", marginTop: 8 }}>{today}</div>
            </div>
          </div>

          {/* Stats */}
          <div className="stats">
            <div className="stat-card">
              <div className="stat-label">{l.cases}</div>
              <div className="stat-value">{hasData ? o.cases.toLocaleString(locale === "ar" ? "ar-SA" : locale) : l.noData}</div>
            </div>
            <div className="stat-card">
              <div className="stat-label">{l.deaths}</div>
              <div className="stat-value red">{hasData ? o.deaths.toLocaleString(locale === "ar" ? "ar-SA" : locale) : l.noData}</div>
            </div>
            <div className="stat-card">
              <div className="stat-label">{l.cfr}</div>
              <div className="stat-value amber">{cfr}</div>
            </div>
          </div>

          {/* Meta */}
          <div className="meta">
            <div className="meta-item">
              <span className="meta-label">{l.date} :</span>
              <span className="meta-value">{o.date}</span>
            </div>
            <div className="meta-item">
              <span className="meta-label">{l.region} :</span>
              <span className="meta-value" style={{ textTransform: "capitalize" }}>{o.region}</span>
            </div>
            {incidence !== null && (
              <div className="meta-item">
                <span className="meta-label">{l.incidence} :</span>
                <span className="meta-value">{incidence.toFixed(2)}</span>
              </div>
            )}
            {getPopulationThousands(o.country_en) && (
              <div className="meta-item">
                <span className="meta-label">Population :</span>
                <span className="meta-value">{((getPopulationThousands(o.country_en) ?? 0) * 1000).toLocaleString(locale === "ar" ? "ar-SA" : locale)}</span>
              </div>
            )}
          </div>

          {/* Description — localized via getLocalizedDescription(), falls back to EN */}
          {o.description && (
            <div className="description">
              <h3>{l.description}</h3>
              <p>{getLocalizedDescription(o, locale)}</p>
            </div>
          )}

          {/* Focal Point Guidance — active outbreaks only */}
          {o.active && (
            <div className="fp-section">
              <div className="fp-header">
                <div className="fp-title">{fp.fpGuidance}</div>
                <div className="fp-tier">{tierLabel}</div>
              </div>
              <div className="fp-actions-label">{fp.firstActions}</div>
              <ul className="fp-actions">
                {fpActions.map((action, i) => (
                  <li key={i}>{action}</li>
                ))}
              </ul>
            </div>
          )}

          {/* Footer */}
          <div className="footer">
            <div>
              <div>{l.generatedBy} — healthwatch-global.com</div>
              <div style={{ marginTop: 4, fontSize: 10 }}>{l.disclaimer}</div>
            </div>
            {o.source && (
              <div style={{ textAlign: isRtl ? "left" : "right" }}>
                <div>{l.source} :</div>
                <a className="source-link" href={o.source}>{o.source}</a>
              </div>
            )}
          </div>

        </div>

        {/* Print button */}
        <button
          className="print-btn no-print"
        >
          🖨️ {l.print}
        </button>

        <script dangerouslySetInnerHTML={{ __html: `
          document.querySelector('.print-btn').addEventListener('click', function() { window.print(); });
        `}} />
      </body>
    </html>
  );
}
